Repository donkim1212/futsal-online, pull requests merged in 2024-06, with the labels that each got.

#18 Merge branch 'feat/validators' to 'develop'
  package.json
  src/middlewares/validators/player-validator.middleware.js
  src/middlewares/validators/user-validator.middleware.js
  yarn.lock
Labels: feature

#17 Merge branch 'feat/error-checker' to 'develop'
  src/lib/errors/classes/not-enough-money.error.js
  src/lib/errors/classes/player-not-found.error.js
  src/lib/errors/classes/user-not-found.error.js
  src/lib/errors/error-checker.js
Labels: feature

#21 errorChecker: teamChecker 기능 추가
  src/lib/errors/classes/team-not-ready.error.js
  src/lib/errors/error-checker.js
Labels: feature

#23 RE: Schema 업데이트 및 PrismaClient 파일 재생성
  prisma/player.schema.prisma
  prisma/player/edge.js
  prisma/player/index-browser.js
  prisma/player/index.d.ts
  prisma/player/index.js
  prisma/player/package.json
  prisma/player/schema.prisma
  prisma/player/wasm.js
  prisma/user.schema.prisma
  prisma/user/edge.js
  prisma/user/index-browser.js
  prisma/user/index.d.ts
  prisma/user/index.js
  prisma/user/package.json
  prisma/user/schema.prisma
  prisma/user/wasm.js
Labels: enhancement

#24 Fix: missing tierName key
  src/routes/players.route.js
Labels: enhancement

#25 Feat/games router
  src/routes/games.route.js
Labels: feature

#29 Update users.route.js
  prisma/user.schema.prisma
  prisma/user/edge.js
  prisma/user/index-browser.js
  prisma/user/index.d.ts
  prisma/user/index.js
  prisma/user/package.json
  prisma/user/schema.prisma
  prisma/user/wasm.js
  src/routes/users.route.js
Labels: feature

#30 users 라우터 bcrypt 오류 수정
  src/middlewares/validators/user-validator.middleware.js
  src/routes/users.route.js
Labels: bugfix

#31 users 라우터 오류 수정 완료
  src/middlewares/auths/user.authenticator.js
  src/middlewares/validators/user-validator.middleware.js
  src/routes/users.route.js
Labels: bugfix

#33 games 라우터 오류 수정
  src/lib/errors/classes/team-not-ready.error.js
  src/lib/errors/error-checker.js
  src/routes/games.route.js
Labels: enhancement, bugfix

#36 Feat/games router matchmaking
  src/routes/games.route.js
Labels: feature

#37 Update: play() now receives opponent as nullable parameter
  src/routes/games.route.js
Labels: bugfix

#39 커스텀 error 클래스 수정
  src/lib/errors/classes/not-enough-money.error.js
  src/lib/errors/classes/player-not-found.error.js
  src/lib/errors/classes/user-not-found.error.js
  src/lib/errors/error-checker.js
Labels: bugfix

#46 Fix: gamesRouter game error, storesRouter gacha error
  src/app.js
  src/lib/errors/error-checker.js
  src/routes/games.route.js
  src/routes/stores.route.js
Labels: bugfix

#48 매치 메이킹 기능 수정 및 매치 큐 테이블 추가
  prisma/user.schema.prisma
  prisma/user/edge.js
  prisma/user/index-browser.js
  prisma/user/index.d.ts
  prisma/user/index.js
  prisma/user/package.json
  prisma/user/schema.prisma
  prisma/user/wasm.js
  src/lib/errors/error-checker.js
  src/routes/games.route.js
  src/routes/teams.route.js
Labels: enhancement

#49 inventory 라우터 기능 수정
  src/lib/utils/tier-utils.js
  src/routes/inventories.route.js
Labels: enhancement

#50 Refactored games router
  src/lib/utils/tier-utils.js
  src/routes/games.route.js
Labels: enhancement

#53 강화 기능 수정
  src/lib/utils/tier-utils.js
  src/routes/stores.route.js
Labels: enhancement

#54 User 테이블에 wins, draws, loses 컬럼 추가 (스키마 변경)
  prisma/user.schema.prisma
  prisma/user/edge.js
  prisma/user/index-browser.js
  prisma/user/index.d.ts
  prisma/user/index.js
  prisma/user/package.json
  prisma/user/schema.prisma
  prisma/user/wasm.js
Labels: enhancement

#55 Update: add MatchHistory table to the user schema
  prisma/user.schema.prisma
  prisma/user/edge.js
  prisma/user/index-browser.js
  prisma/user/index.d.ts
  prisma/user/index.js
  prisma/user/package.json
  prisma/user/schema.prisma
  prisma/user/wasm.js
Labels: enhancement

#56 Fix/routers
  src/lib/errors/error-checker.js
  src/routes/games.route.js
  src/routes/rankings.route.js
  src/routes/users.route.js
Labels: enhancement

#57 Update README.md
  README.md
Labels: documentation

#58 Test/tier
  src/app.js
  src/routes/tier.route.js
Labels: feature
